#ifndef GLOBAL_FX_PASS_ENABLED
#define GLOBAL_FX_PASS_ENABLED 0 ///+
#endif

#ifndef DEFAULT_SHADOW_VSM_RESOLUTION
#define DEFAULT_SHADOW_VSM_RESOLUTION 512
#endif

#ifndef DEFAULT_SHADOW_CSM_RESOLUTION
#define DEFAULT_SHADOW_CSM_RESOLUTION 4096
#endif

#ifndef GLOBAL_FRUSTUM_ENABLED
#define GLOBAL_FRUSTUM_ENABLED 1 ///+
#endif

#ifndef GLOBAL_FRUSTUM_DEBUG_DRAW
#define GLOBAL_FRUSTUM_DEBUG_DRAW 0 ///+
#endif

#ifndef GLOBAL_FRUSTUM_FOV_MULTIPLIER
#define GLOBAL_FRUSTUM_FOV_MULTIPLIER 1.0f ///+
#endif

#ifndef ENABLE_REVERSE_Z
#define ENABLE_REVERSE_Z 0 //ifdef(ems, 0, 1) ///+
#endif

#ifndef MAX_LIGHTS
#define MAX_LIGHTS 96
#endif

#ifndef MAX_SHADOW_LIGHTS
#define MAX_SHADOW_LIGHTS 8
#endif

#ifndef NUM_SHADOW_CASCADES
#define NUM_SHADOW_CASCADES 4
#endif

#ifndef SHADOW_CASCADE_BLEND_REGION
#define SHADOW_CASCADE_BLEND_REGION 0.8f
#endif
